# Generated by Django 5.0.6 on 2024-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(blank=True, max_length=12, null=True)),
                ('course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=1000, null=True)),
                ('subscribers', models.IntegerField(blank=True, null=True)),
                ('num_lectures', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100, null=True)),
                ('content_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, choices=[('Business Finance', 'Business Finance'), ('Computer Science', 'Computer Science'), ('Musical Instrument', 'Musical Instrument'), ('Graphic Design', 'Graphic Design')], max_length=500, null=True)),
                ('published_timestamp', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
